[package]
name = "xelis-environment"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
better_any = "0.2.0"
hashbrown = "0.15.2"
indexmap = "2.7.0"
thiserror = "2.0.1"
xelis-types = { path = "../types" }
